# Generated by Django 2.0.4 on 2019-02-11 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=250, unique_for_date='created')),
                ('description', models.TextField()),
                ('job_role', models.CharField(choices=[('Full Stack Developer', 'Full Stack Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend  Developer', 'Backend  Developer'), ('Android  Developer', 'Android  Developer'), ('Graphic Designer', 'Graphic Designer'), ('IOS Developer', 'IOS Developer'), ('Data Scientist', 'Data Scientist')], default='Full Stack Developer', max_length=30)),
                ('dev_experience', models.CharField(choices=[('Entry', 'Entry'), ('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior')], default='Mid-Level', max_length=30)),
                ('engagement_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], default='Full-time', max_length=30)),
                ('tech_stack', models.CharField(max_length=500)),
                ('num_devs_wanted', models.IntegerField(default=1)),
                ('remuneration', models.CharField(help_text='in dollars ($)', max_length=45)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position_filled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='marketplace.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.Person')),
                ('linkedin_url', models.CharField(max_length=500, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=500, null=True)),
                ('github_repo', models.CharField(max_length=500, null=True)),
                ('language', models.CharField(blank=True, max_length=140, null=True)),
                ('framework', models.CharField(blank=True, max_length=140, null=True)),
                ('years', models.CharField(choices=[('1-2', '1-2'), ('2-4', '2-4'), ('4-above', '4-above')], max_length=30, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('availability', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=30, null=True)),
            ],
            bases=('marketplace.person',),
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.Person')),
                ('company', models.CharField(blank=True, max_length=140, null=True)),
                ('job_role', models.CharField(blank=True, max_length=140, null=True)),
                ('industry', models.CharField(blank=True, max_length=80, null=True)),
                ('company_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            bases=('marketplace.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applied_by',
            field=models.ManyToManyField(related_name='applied_jobs', to='marketplace.Developer'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='recommended_devs',
            field=models.ManyToManyField(blank=True, related_name='recommended_jobs', to='marketplace.Developer'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='selected_devs',
            field=models.ManyToManyField(blank=True, related_name='jobs_picked_for', to='marketplace.Developer'),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='marketplace.Recruiter'),
        ),
    ]
