# Generated by Django 2.0.4 on 2019-02-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='recommended_devs',
        ),
    ]
