# Generated by Django 2.0.4 on 2019-02-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_by', models.ManyToManyField(related_name='applied_jobs', to='marketplace.Developer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='marketplace.Job')),
                ('recommended_devs', models.ManyToManyField(blank=True, related_name='recommended_jobs', to='marketplace.Developer')),
                ('selected_devs', models.ManyToManyField(blank=True, related_name='jobs_picked_for', to='marketplace.Developer')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobstatistic',
            name='applied_by',
        ),
        migrations.RemoveField(
            model_name='jobstatistic',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobstatistic',
            name='recommended_devs',
        ),
        migrations.RemoveField(
            model_name='jobstatistic',
            name='selected_devs',
        ),
        migrations.DeleteModel(
            name='JobStatistic',
        ),
    ]
