# Generated by Django 2.0.4 on 2019-02-21 14:11

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_jobapplication_recommended_devs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
