# Generated by Django 2.0.4 on 2019-02-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20190208_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='availability',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='dev_experience',
            field=models.CharField(choices=[('Entry', 'Entry'), ('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior')], default='mid-level', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='engagement_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], default='full_time', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_role',
            field=models.CharField(choices=[('Full Stack Developer', 'Full Stack Developer'), ('Frontend Developer', 'Frontend Developer'), ('backend_developer', 'Backend  Developer'), ('Android  Developer', 'Android  Developer'), ('Graphic Designer', 'Graphic Designer'), ('IOS Developer', 'IOS Developer'), ('Data Scientist', 'Data Scientist')], default='full_stack_developer', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True),
        ),
    ]
